var mongoose = require('mongoose');
var ProductSchema = new mongoose.Schema(
  {
    commoncode:{},
    ItemCode:{},
    Description:{},
    Code:{},
    Rate:{},
    std:{},
    Unit:{},
    Unitvalue:{},
    Quantity:{},
    Calquantityvalue:{},
    CalUnitvalue:{},
    Amount:{},
    labour_facor:{},
    labourcost:{},
    cartage:{},
    cartagecost:{},
    Water:{},
    watercost:{},
    gst:{},
    gstcost:{},
    Overheads:{},
    overcost:{},
   cess:{},
   cesscost:{},

    Civ_Elec:{},
    schyear:{},
    Stages:{},
    Ratestype:{},
 Username:{},
    subheads:{},
    usercalquan:{},
    userunit:{},
    srnsr:{},
    date:{}
    
// Slno : {},
// Username:{},
// Islno:{},        
// ItemCode:{},
// MLCode: {},
// Icode:{},
// Code :{},
// Description:{},
// Calquantityvalue:{},
// CalUnitvalue: {},
// Unitvalue:{},
// weightage: {},
// Unit: {},
// Quantity:{},
// particularqty:{},
// Actualquantity:{},
// Rate:{},
// Rate2007:{},
// Amount: {},
// Amount1:{},
// worktype: {},
// Stages:{},
// Water: {},
// watercost: {},
// Overheads:{},
// overheadcost: {},
// Total:{},
// Itemtotal: {},
// Calquantity:{},
// Caltotal:{},
// sno: {},
// cartage: {},
// cartagecost:{},
// Civ_Elec:{},
// labour_facor:{},
// labourcost:{},
// eq_fac: {},
// eq_fac_phy:{},
// schyear:{},
// Wastage_desc:{},
// Wastage:{},
// sr_nsr:{},
// cesscost:{},
// gstcost:{},
// gst:{},
// cess:{},
                  
});
module.exports = mongoose.model('A', ProductSchema,'a');
