var mongoose = require('mongoose');
var SrSchema = new mongoose.Schema(
 {
    // _id:String,
Slno : Number,
 Itemcode :  {},
 Description :String,
 Unitvalue :  Number,
 Unit :  String,
 Rate : Number,
 currentrate: Number,
 SubHeadCode:Number,
 SubHeadDes : String,
 MasterCode :String ,
 MasterCode1 :  Number,
 MasterDesc : String,
 SubMasterCode : String ,
 SubMasterCode1 : Number ,
 SubMasterDesc :  String,
 SubCode : String  ,
 SubCode1 : Number ,
 SubDesc :String,
 SSubCode : String ,
 SSubCode1 :Number,
 SSubDesc : String,
 Edit : String,
 SR_NSR : String,
 Pub_pri : String,
 Username : String,
 Calquantity :Number,
 Deviation : Number,
 Civ_Elec :String,
 ulength : String,
 ubreadth :String,
 uheight : String,
 schyear:  Number,
 Depttype : String  },
);
module.exports = mongoose.model('Sr2007',SrSchema,'sr2007');