var mongoose=require('mongoose');
var TrySchema = new mongoose.Schema(
    {
        _id:String,
        Slno : String,
        Username:String,
        Islno: Number,        
        ItemCode: {},
        MLCode: String,
        Icode: {},
        Code :{},
        Description:String,
        Calquantityvalue:Number
,        CalUnitvalue: Number,
        Unitvalue: Number,
        weightage: Number,
        Unit: Number,
        Quantity: {},
        particularqty: Number,
        Actualquantity: Number,
        Rate:{},
        Rate2007: Number,
        Amount: Number,
        Amount1: Number,
        worktype: String,
        Stages:Number,
        Water: Number,
        watercost: Number,
        Overheads: Number,
        overheadcost: Number,
        Total:Number,
        Itemtotal: Number,
        Calquantity: Number,
        Caltotal: Number,
        sno: Number,
        cartage: Number,
        cartagecost: Number,
        Civ_Elec: String,
        labour_facor: Number,
        labourcost: Number,
        eq_fac: Number,
        eq_fac_phy:Number,
        schyear: {},
        Wastage_desc:String,
        Wastage: Number,
        sr_nsr: Number,
        

    });
module.exports = mongoose.model('Try',TrySchema,'try');